### ISSUE TITLE
Server unable to handle multiple requests

### ISSUE THREAD

**Issue by HeshamAmer** [pact-foundation/pact-stub-server-archived#12]
Hello, 
We were using the pact-stub-server on version 0.2.1, however we realized that it's not fast enough. 
Our microservice was running on springBoot and does 2 syncrhonous calls in succession, however the pact server is only able to respond to the first one, and on the second one we get a I/O error and we don't see any requests going the pact server. 
It seems that the pact-server doesn't close the port quick enough? something in that matter that caused it to not being able to react fast enough to the second request.
If you want code samples or versioning please write me, We fixed it by switching to mock-server but it'd be nice if we can still use the pact-server.

**Comment by uglyog** [comment]
Code samples and logs will definitely help.
