### ISSUE TITLE
Running of 0.1.0 (latest) docker image fails with libssl.so not found error

### ISSUE THREAD

**Issue by assafw** [pact-foundation/pact-stub-server-archived#4]
Hi,

On OSX 10.13.6 (High-Sierra)
Docker CE: tested on both `18.03.1-ce-mac65 (24312)` and `18.06.0-ce-mac70 (26399)` (both are on the stable channel)
 
command: 
```
docker run -t -p 7777:7777 -v "$(pwd)/project/pacts:/app/pacts" pactfoundation/pact-stub-server -p 7777 -d pacts
```

fails with the following output:

```
/app/pact-stub-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

when trying with tagged image v0.0.10 it's working fine

**Comment by dash1291** [comment]
I'm also getting this error

**Comment by uglyog** [comment]
Images have been corrected, try again with the latest.
