### ISSUE TITLE
Ignores docker-stop

### ISSUE THREAD

**Issue by pkubowicz** [pact-foundation/pact-stub-server-archived#8]
When using 'docker stop' the container is stopped after 10 seconds. This means that SIGTERM is not enough and docker-stop sends SIGKILL.

Dockerfile uses exec form of ENTRYPOINT (https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/), so I don't understand why SIGTERM does not work. Maybe some magic with Rust comes into play.

**Comment by uglyog** [comment]
More likely Hyper is not responding to it and shutting the server threads down. I'll have a look into it.
